// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// import 'package:firebase_core/firebase_core.dart';
 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0aoAAUSshwfiw6x-Uq1-Bq06SyUpdAK4',
    appId: '1:68583673381:web:170438521b26d6455c39cc',
    messagingSenderId: '68583673381',
    projectId: 'fyplogin-fcdfd',
    authDomain: 'fyplogin-fcdfd.firebaseapp.com',
    storageBucket: 'fyplogin-fcdfd.appspot.com',
    measurementId: 'G-6THH1HSBCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGJqf_dpvjlJJV4PZxd7GiupblmdXJ3w',
    appId: '1:68583673381:android:7e66c710273a77355c39cc',
    messagingSenderId: '68583673381',
    projectId: 'fyplogin-fcdfd',
    storageBucket: 'fyplogin-fcdfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0pSzU0RuFXh60HtEv8bczCpD3Z1alUEc',
    appId: '1:68583673381:ios:bbaa3665163ee88c5c39cc',
    messagingSenderId: '68583673381',
    projectId: 'fyplogin-fcdfd',
    storageBucket: 'fyplogin-fcdfd.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0pSzU0RuFXh60HtEv8bczCpD3Z1alUEc',
    appId: '1:68583673381:ios:bbaa3665163ee88c5c39cc',
    messagingSenderId: '68583673381',
    projectId: 'fyplogin-fcdfd',
    storageBucket: 'fyplogin-fcdfd.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0aoAAUSshwfiw6x-Uq1-Bq06SyUpdAK4',
    appId: '1:68583673381:web:9cebf97c1fbe7d865c39cc',
    messagingSenderId: '68583673381',
    projectId: 'fyplogin-fcdfd',
    authDomain: 'fyplogin-fcdfd.firebaseapp.com',
    storageBucket: 'fyplogin-fcdfd.appspot.com',
    measurementId: 'G-BPR4VE73PY',
  );

}